// data/testimonials.data.ts

export interface Testimonial {
    text: string;
    author: string;
    role: string;
    rating: number;
  }
  
  export const testimonials: Testimonial[] = [
    { text: "Servicio excepcional, siempre puntuales y confiables.", author: "María González", role: "Ejecutiva", rating: 5 },
    { text: "Vehículos impecables y atención de primera.", author: "Carlos Ruiz", role: "Empresario", rating: 5 },
    { text: "Totalmente recomendado, gran calidad.", author: "Ana Torres", role: "Directora", rating: 4 },
    { text: "Conductores profesionales y amables.", author: "Luis Pérez", role: "Gerente", rating: 5 },
    { text: "O melhor serviço de transporte que já experimentei.", author: "Sofía López", role: "Consultora", rating: 5 },
    { text: "Siempre mi primera opción para viajes.", author: "Javier Díaz", role: "Abogado", rating: 4 },
    { text: "Atención al cliente sobresaliente.", author: "Elena Martínez", role: "Doctora", rating: 5 },
    { text: "Vehículos cómodos y servicio confiable.", author: "Andrés Gómez", role: "Ingeniero", rating: 5 },
    { text: "Gran experiencia, muy profesionales.", author: "Laura Sánchez", role: "Diseñadora", rating: 4 },
    { text: "Siempre superan mis expectativas.", author: "Miguel Fernández", role: "Contador", rating: 5 },
    { text: "Servicio de lujo a precio justo.", author: "Carmen Vargas", role: "Empresaria", rating: 5 },
    { text: "Conductores atentos y puntuales.", author: "Pedro Morales", role: "Arquitecto", rating: 4 },
    { text: "Mejor servicio de transporte en la ciudad.", author: "Isabel Romero", role: "Periodista", rating: 5 },
    { text: "Vehículos modernos y cómodos.", author: "Ricardo Castro", role: "Programador", rating: 5 },
    { text: "Siempre una experiencia agradable.", author: "Clara Ortiz", role: "Marketing", rating: 4 },
    { text: "Recomendado al 100% por su calidad.", author: "Daniel Herrera", role: "Consultor", rating: 5 },
    { text: "Always reliable and punctual.", author: "Martín Acosta", role: "Consultant", rating: 5 },
    { text: "Servicio confiable y de alto nivel.", author: "Felipe Rojas", role: "Médico", rating: 4 },
    { text: "Vehículos impecables, conductores amables.", author: "Mónica Silva", role: "Gerente", rating: 5 },
    { text: "Siempre puntuales, nunca fallan.", author: "Gabriel Mendoza", role: "Emprendedor", rating: 5 },
    { text: "Una experiencia de transporte premium.", author: "Valeria Cruz", role: "Publicista", rating: 4 },
    { text: "Atención personalizada y profesional.", author: "Óscar Navarro", role: "Ingeniero", rating: 5 },
    { text: "El mejor servicio que he probado.", author: "Lorena Ramírez", role: "Directora", rating: 5 },
    { text: "Conductores que inspiran confianza.", author: "Héctor Luna", role: "Contador", rating: 4 },
    { text: "Siempre una experiencia de calidad.", author: "Natalia Paredes", role: "Diseñadora", rating: 5 },
    { text: "Servicio confiable para cualquier ocasión.", author: "Eduardo Vega", role: "Empresario", rating: 5 },
    { text: "Vehículos de lujo y gran servicio.", author: "Camila Rivas", role: "Consultora", rating: 4 },
    { text: "Recomendado por su profesionalismo.", author: "Sebastián Campos", role: "Abogado", rating: 5 },
    { text: "Atención impecable en cada viaje.", author: "Verónica Peña", role: "Doctora", rating: 5 },
    { text: "Siempre a tiempo y muy amables.", author: "Ignacio Salazar", role: "Arquitecto", rating: 4 },
    { text: "Servicio de primera, muy satisfecho.", author: "Juliana Méndez", role: "Periodista", rating: 5 },
    { text: "Always punctual, they never fail.", author: "Gabriel Mendoza", role: "Entrepreneur", rating: 5 },
    { text: "Gran experiencia en cada viaje.", author: "Teresa Delgado", role: "Marketing", rating: 4 },
    { text: "Always reliable and punctual.", author: "Martín Acosta", role: "Consultant", rating: 5 },
    { text: "Vehículos cómodos, servicio excelente.", author: "Lucía Bravo", role: "Abogada", rating: 5 },
    { text: "Recomendado por su calidad.", author: "Diego Pineda", role: "Médico", rating: 4 },
    { text: "Atención al cliente de alto nivel.", author: "Marina Flores", role: "Gerente", rating: 5 },
    { text: "Servicio premium, muy profesional.", author: "Álvaro Cordero", role: "Emprendedor", rating: 5 },
    { text: "Conductores amables y puntuales.", author: "Paola Guzmán", role: "Publicista", rating: 4 },
    { text: "Siempre una gran experiencia.", author: "Leonardo Suárez", role: "Ingeniero", rating: 5 },
    { text: "El mejor transporte que he usado.", author: "Adriana Molina", role: "Directora", rating: 5 },
    { text: "Servicio confiable y de calidad.", author: "Tomás Peralta", role: "Contador", rating: 4 },
    { text: "Vehículos impecables y modernos.", author: "Rebeca Salazar", role: "Diseñadora", rating: 5 },
    { text: "Atención personalizada, excelente.", author: "Simón Arango", role: "Empresario", rating: 5 },
    { text: "Siempre puntuales y confiables.", author: "Estela Quiroz", role: "Consultora", rating: 4 },
    { text: "Servicio de lujo, muy recomendado.", author: "Fabio Villalba", role: "Abogado", rating: 5 },
    { text: "Conductores profesionales, gran experiencia.", author: "Lina Escobar", role: "Doctora", rating: 5 },
    { text: "Siempre superan las expectativas.", author: "Emilio Tovar", role: "Arquitecto", rating: 4 },
    { text: "Servicio confiable y de alto nivel.", author: "Sara Montero", role: "Periodista", rating: 5 },
    { text: "Gran calidad en cada detalle.", author: "Juan Esteban", role: "Programador", rating: 5 },
  ];